name: release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  goreleaser:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Import GPG key (optional)
        id: import_gpg
        continue-on-error: true
        uses: crazy-max/ghaction-import-gpg@v5.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Run GoReleaser (with signing)
        if: ${{ steps.import_gpg.outputs.fingerprint != '' }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.24.0
          args: release --rm-dist --config .goreleaser.yaml
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser (skip signing)
        if: ${{ steps.import_gpg.outputs.fingerprint == '' }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.24.0
          args: release --rm-dist --config .goreleaser.yaml --skip=sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
